#!/usr/bin/env bash
# inventory 라벨 자동 생성: 각 skill/agent에 시간 불변성/이식성/도메인 특수성 라벨 부여
#
# 출력: .claude/inventory-labels.yml (inventory.yml과 분리, 형식 안정성 유지)
#
# 라벨 정의:
#   model_dependency : high (모델/시간 가변) | low (안정적, 도메인 패턴)
#                      → AI 관련 기술은 high (모델 발전 시 약화)
#   portability      : universal (모든 도구 적용) | claude-only (Claude 전용)
#                      → Slash command, Subagent, .claude/agents 직접 의존이면 claude-only
#   domain_specificity : project-specific | general
#                        → business/legal/operations 카테고리는 project-specific
#   last_modified    : git log 기반 (YYYY-MM-DD)
#
# 사용:
#   ./scripts/generate-inventory-labels.sh           # 생성 + 리포트
#   ./scripts/generate-inventory-labels.sh report    # 리포트만 (생성 X)
#   ./scripts/generate-inventory-labels.sh validate  # 라벨 freshness 체크 (CI용)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/.claude/skills"
AGENTS_DIR="$REPO_ROOT/.claude/agents"
OUTPUT="$REPO_ROOT/.claude/inventory-labels.yml"

cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# 휴리스틱: model_dependency
# ---------------------------------------------------------------------------
# high 조건 (어느 하나라도 만족):
#   - 카테고리가 ai
#   - 파일명이 -ai로 끝나거나 -ai- 포함
#   - 본문에 AI 핵심 키워드 5회 이상 (claude/anthropic/llm/agentic/genai)
classify_model_dependency() {
    local file="$1"
    local category="$2"
    local name
    name=$(basename "$file" .md)

    if [[ "$category" == "ai" ]]; then
        echo "high"; return
    fi
    if [[ "$name" =~ (^|-)ai(-|$) ]] || [[ "$name" =~ -genai$ ]] || [[ "$name" =~ -llm($|-) ]]; then
        echo "high"; return
    fi
    local hits
    hits=$(grep -ciE 'claude|anthropic|\bllm\b|agentic|genai' "$file" 2>/dev/null || echo 0)
    hits=${hits//[^0-9]/}
    if [[ -n "$hits" && "$hits" -ge 5 ]]; then
        echo "high"; return
    fi
    echo "low"
}

# ---------------------------------------------------------------------------
# 휴리스틱: portability
# ---------------------------------------------------------------------------
# claude-only 조건 (cross-link은 제외, 진짜 의존만 카운트):
#   - subagent_type (Agent tool 호출)
#   - Agent(...) / Skill(...) 직접 호출
#   - .claude/agents/ 또는 .claude/commands/ 참조 (commands는 Claude-only)
#   - 본문에서 ^/명령어 형태 슬래시 커맨드
# .claude/skills/...는 cross-link이라 제외 — 모든 도구가 같은 디렉토리 쓸 수 있음
classify_portability() {
    local file="$1"
    local hits
    hits=$(grep -cE 'subagent_type|Agent\(|Skill\(|\.claude/(agents|commands)/|^/[a-z][a-z0-9_-]+($|[ :])' "$file" 2>/dev/null || echo 0)
    hits=${hits//[^0-9]/}
    if [[ -n "$hits" && "$hits" -ge 2 ]]; then
        echo "claude-only"
    else
        echo "universal"
    fi
}

# ---------------------------------------------------------------------------
# 휴리스틱: domain_specificity
# ---------------------------------------------------------------------------
classify_domain_specificity() {
    local category="$1"
    case "$category" in
        business|legal|operations) echo "project-specific" ;;
        *) echo "general" ;;
    esac
}

# ---------------------------------------------------------------------------
# git log 기반 last_modified
# ---------------------------------------------------------------------------
get_last_modified() {
    local file="$1"
    git log -1 --format='%aI' -- "$file" 2>/dev/null | cut -d'T' -f1 || echo "unknown"
}

# ---------------------------------------------------------------------------
# Main: skills/agents 순회하며 라벨 부여
# ---------------------------------------------------------------------------
generate_labels() {
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    local tmp
    tmp=$(mktemp)

    {
        echo "# Auto-generated by scripts/generate-inventory-labels.sh"
        echo "# 직접 수정하지 마세요. 스크립트 재실행으로 갱신."
        echo "generated: \"$timestamp\""
        echo ""
        echo "# 라벨 의미:"
        echo "#   model_dependency  : high(시간 가변) / low(안정적)"
        echo "#   portability       : universal(모든 도구) / claude-only"
        echo "#   domain_specificity: project-specific / general"
        echo "#   last_modified     : git log 기반 (YYYY-MM-DD)"
        echo ""
        echo "skills:"

        # category | name | model_dep | portability | domain_spec | last_mod
        local entries=()
        while IFS= read -r file; do
            local rel="${file#"$SKILLS_DIR"/}"
            local category="${rel%%/*}"
            [[ "$category" == "$rel" ]] && category="other"
            local name
            name=$(basename "$file" .md)

            local md po ds lm
            md=$(classify_model_dependency "$file" "$category")
            po=$(classify_portability "$file")
            ds=$(classify_domain_specificity "$category")
            lm=$(get_last_modified "$file")

            entries+=("${category}|${name}|${md}|${po}|${ds}|${lm}")
        done < <(find "$SKILLS_DIR" -type f -name "*.md" | sort)

        local prev_cat=""
        printf '%s\n' "${entries[@]}" | sort -t'|' -k1,1 -k2,2 | while IFS='|' read -r cat name md po ds lm; do
            if [[ "$cat" != "$prev_cat" ]]; then
                echo "  $cat:"
                prev_cat="$cat"
            fi
            echo "    - name: $name"
            echo "      model_dependency: $md"
            echo "      portability: $po"
            echo "      domain_specificity: $ds"
            echo "      last_modified: \"$lm\""
        done

        echo ""
        echo "agents:"

        # agents는 카테고리 분류는 generate-inventory.sh와 동일하지 않게 단순화
        local agent_entries=()
        for file in "$AGENTS_DIR"/*.md; do
            [[ -f "$file" ]] || continue
            local name
            name=$(basename "$file" .md)
            # category는 inventory.yml과 일관성을 위해 단순 추론 (필요 시 generate-inventory.sh 호출 가능)
            local category="agent"
            local md po lm
            md=$(classify_model_dependency "$file" "$category")
            po=$(classify_portability "$file")
            lm=$(get_last_modified "$file")
            # agents는 모두 claude-only로 단정 (Subagent는 Claude 고유 메커니즘)
            po="claude-only"
            agent_entries+=("${name}|${md}|${po}|${lm}")
        done

        printf '%s\n' "${agent_entries[@]}" | sort -t'|' -k1,1 | while IFS='|' read -r name md po lm; do
            echo "  - name: $name"
            echo "    model_dependency: $md"
            echo "    portability: $po"
            echo "    last_modified: \"$lm\""
        done
    } > "$tmp"

    # Timestamp 보존: 내용이 동일하면 기존 timestamp 유지 (CI freshness 안정화)
    if [[ -f "$OUTPUT" ]]; then
        local old_no_ts new_no_ts
        old_no_ts=$(grep -v '^generated:' "$OUTPUT" 2>/dev/null || true)
        new_no_ts=$(grep -v '^generated:' "$tmp" 2>/dev/null || true)
        if [[ "$old_no_ts" == "$new_no_ts" ]]; then
            local old_ts
            old_ts=$(grep '^generated:' "$OUTPUT" | head -1)
            sed -i.bak "s/^generated:.*/${old_ts//\//\\/}/" "$tmp"
            rm -f "$tmp.bak"
        fi
    fi

    mv "$tmp" "$OUTPUT"
    printf 'Generated %s\n' "$OUTPUT"
}

# ---------------------------------------------------------------------------
# 분포 리포트
# ---------------------------------------------------------------------------
report() {
    [[ -f "$OUTPUT" ]] || { printf 'inventory-labels.yml 없음. generate 먼저 실행.\n' >&2; exit 1; }

    printf '\n=== Skills 라벨 분포 ===\n'
    printf '\n[model_dependency]\n'
    awk '/^skills:/{f=1; next} /^agents:/{f=0} f && /model_dependency:/' "$OUTPUT" \
        | sed 's/.*model_dependency: //' | sort | uniq -c | sort -rn
    printf '\n[portability]\n'
    awk '/^skills:/{f=1; next} /^agents:/{f=0} f && /portability:/' "$OUTPUT" \
        | sed 's/.*portability: //' | sort | uniq -c | sort -rn
    printf '\n[domain_specificity]\n'
    awk '/^skills:/{f=1; next} /^agents:/{f=0} f && /domain_specificity:/' "$OUTPUT" \
        | sed 's/.*domain_specificity: //' | sort | uniq -c | sort -rn

    printf '\n=== Agents 라벨 분포 ===\n'
    printf '\n[model_dependency]\n'
    awk '/^agents:/{f=1} f && /model_dependency:/' "$OUTPUT" \
        | sed 's/.*model_dependency: //' | sort | uniq -c | sort -rn

    printf '\n=== Skills model_dependency=high ===\n'
    awk '
        /^skills:/ {section="skills"; next}
        /^agents:/ {section="agents"; next}
        section=="skills" && /^  [a-z][a-z-]*:$/ {cat=$1; sub(/:/,"",cat)}
        section=="skills" && /^    - name:/ {n=split($0,p,": "); name=p[2]}
        section=="skills" && /model_dependency: high/ {print "  " cat "/" name}
    ' "$OUTPUT" | sort -u

    printf '\n=== Skills portability=claude-only ===\n'
    awk '
        /^skills:/ {section="skills"; next}
        /^agents:/ {section="agents"; next}
        section=="skills" && /^  [a-z][a-z-]*:$/ {cat=$1; sub(/:/,"",cat)}
        section=="skills" && /^    - name:/ {n=split($0,p,": "); name=p[2]}
        section=="skills" && /portability: claude-only/ {print "  " cat "/" name}
    ' "$OUTPUT" | sort -u
}

validate() {
    local tmp
    tmp=$(mktemp)
    OUTPUT="$tmp" generate_labels >/dev/null 2>&1

    local old_no_ts new_no_ts
    old_no_ts=$(grep -v '^generated:' "$REPO_ROOT/.claude/inventory-labels.yml" 2>/dev/null || true)
    new_no_ts=$(grep -v '^generated:' "$tmp" 2>/dev/null || true)
    if [[ "$old_no_ts" == "$new_no_ts" ]]; then
        printf 'OK  inventory-labels.yml is up to date\n'
        rm -f "$tmp"
        return 0
    else
        printf 'FAIL  inventory-labels.yml is outdated. Run: ./scripts/generate-inventory-labels.sh\n'
        diff <(printf '%s\n' "$old_no_ts") <(printf '%s\n' "$new_no_ts") | head -40 || true
        rm -f "$tmp"
        return 1
    fi
}

case "${1:-generate}" in
    generate)
        generate_labels
        report
        ;;
    report)
        report
        ;;
    validate)
        validate
        ;;
    -h|--help|help)
        sed -n '2,21p' "$0"
        ;;
    *)
        printf 'unknown: %s\n사용법: %s [generate|report|validate]\n' "$1" "$0" >&2
        exit 1
        ;;
esac
