#!/usr/bin/env bash
# generate-inventory.sh - Generate .claude/inventory.yml from skills and agents
# Usage: ./scripts/generate-inventory.sh [generate|validate]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/.claude/skills"
AGENTS_DIR="$REPO_ROOT/.claude/agents"
OUTPUT="$REPO_ROOT/.claude/inventory.yml"

# Category mapping for skills (filename prefix -> category)
categorize_skill() {
  local name="$1"
  case "$name" in
    go-*|concurrency-go|refactoring-go) echo "go" ;;
    spring-*|concurrency-spring|refactoring-spring) echo "spring" ;;
    msa-*|database-sharding|high-traffic-*|api-design|distributed-lock) echo "msa" ;;
    k8s-gpu*) echo "platform" ;;
    k8s-*|istio-*|gateway-*|crossplane-*) echo "kubernetes" ;;
    observability-*|ebpf-*|monitoring-*|logging-*|aiops*|alerting-*) echo "observability" ;;
    sre-*|cicd-*|gitops-*|deployment-*|chaos-*|disaster-*|ephemeral-*|load-testing*|finops*|supply-chain-*) echo "sre" ;;
    backstage|golden-*|ml-*|mlops*|llmops|wasm-*|platform-*) echo "platform" ;;
    dx-*|docs-*|token-*) echo "dx" ;;
    aws-*|terraform-*|kafka*|database*|docker*) echo "infrastructure" ;;
    conventional-commits|git-workflow|refactoring-principles) echo "dx" ;;
    *) echo "other" ;;
  esac
}

# Category mapping for agents
categorize_agent() {
  local name="$1"
  case "$name" in
    go-expert) echo "go" ;;
    java-expert) echo "spring" ;;
    k8s-*|platform-engineer) echo "kubernetes" ;;
    otel-expert) echo "observability" ;;
    security-scanner|anti-bot|terraform-reviewer) echo "security" ;;
    ci-optimizer|git-workflow|pr-review-bot|code-reviewer|ticketing-expert) echo "devops" ;;
    incident-responder) echo "sre" ;;
    load-tester*) echo "testing" ;;
    database-expert*) echo "database" ;;
    finops-*|cost-analyzer) echo "finops" ;;
    mlops-expert) echo "platform" ;;
    *) echo "other" ;;
  esac
}

# Escape YAML special characters in a string
yaml_escape() {
  local s="$1"
  # Replace backslash, then double quotes
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  echo "$s"
}

# Extract metadata from a skill file (# Title on line 1, description on line 3)
extract_skill_meta() {
  local file="$1"
  local lines
  lines=$(wc -l < "$file" | tr -d ' ')
  local title
  title=$(head -1 "$file" | sed 's/^# //')
  local desc
  desc=$(sed -n '3p' "$file")
  echo "$lines|$title|$desc"
}

# Extract metadata from an agent file (YAML front matter + # Title after ---)
extract_agent_meta() {
  local file="$1"
  local lines
  lines=$(wc -l < "$file" | tr -d ' ')
  local first_line
  first_line=$(head -1 "$file")

  local title desc
  if [ "$first_line" = "---" ]; then
    # Has YAML front matter: title from first # heading after ---, desc from front matter
    title=$(awk '/^---$/{n++; next} n>=1 && /^# /{sub(/^# /,""); print; exit}' "$file")
    desc=$(awk '/^---$/{n++; next} n==1 && /^description:/{sub(/^description: *"?/,""); sub(/"$/,""); print; exit}' "$file")
  else
    # No front matter: same format as skills (# Title on line 1, desc on line 3)
    title=$(head -1 "$file" | sed 's/^# //')
    desc=$(sed -n '3p' "$file")
  fi
  echo "$lines|$title|$desc"
}

generate() {
  local tmp
  tmp=$(mktemp)
  local timestamp
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  # Collect skill data: category|name|lines|title|desc
  declare -a skill_entries=()
  local total_skill_lines=0
  local skill_count=0

  for file in "$SKILLS_DIR"/*.md; do
    [ -f "$file" ] || continue
    local basename
    basename=$(basename "$file" .md)
    local meta
    meta=$(extract_skill_meta "$file")
    local lines title desc category
    lines=$(echo "$meta" | cut -d'|' -f1)
    title=$(echo "$meta" | cut -d'|' -f2)
    desc=$(echo "$meta" | cut -d'|' -f3-)
    category=$(categorize_skill "$basename")
    skill_entries+=("$category|$basename|$lines|$title|$desc")
    total_skill_lines=$((total_skill_lines + lines))
    skill_count=$((skill_count + 1))
  done

  # Collect agent data
  declare -a agent_entries=()
  local total_agent_lines=0
  local agent_count=0

  for file in "$AGENTS_DIR"/*.md; do
    [ -f "$file" ] || continue
    local basename
    basename=$(basename "$file" .md)
    local meta
    meta=$(extract_agent_meta "$file")
    local lines title desc category
    lines=$(echo "$meta" | cut -d'|' -f1)
    title=$(echo "$meta" | cut -d'|' -f2)
    desc=$(echo "$meta" | cut -d'|' -f3-)
    category=$(categorize_agent "$basename")
    agent_entries+=("$category|$basename|$lines|$title|$desc")
    total_agent_lines=$((total_agent_lines + lines))
    agent_count=$((agent_count + 1))
  done

  # Write YAML
  {
    echo "# Auto-generated by scripts/generate-inventory.sh"
    echo "# 직접 수정하지 마세요. 스크립트로 재생성하세요."
    echo "generated: \"$timestamp\""
    echo ""
    echo "summary:"
    echo "  skills: { count: $skill_count, total_lines: $total_skill_lines }"
    echo "  agents: { count: $agent_count, total_lines: $total_agent_lines }"
    echo ""

    # Skills by category
    echo "skills:"
    local prev_cat=""
    # Sort by category then name
    printf '%s\n' "${skill_entries[@]}" | sort -t'|' -k1,1 -k2,2 | while IFS='|' read -r cat name lines title desc; do
      if [ "$cat" != "$prev_cat" ]; then
        echo "  $cat:"
        prev_cat="$cat"
      fi
      echo "    - name: $name"
      echo "      lines: $lines"
      echo "      title: \"$(yaml_escape "$title")\""
      echo "      desc: \"$(yaml_escape "$desc")\""
    done

    echo ""

    # Agents by category
    echo "agents:"
    prev_cat=""
    printf '%s\n' "${agent_entries[@]}" | sort -t'|' -k1,1 -k2,2 | while IFS='|' read -r cat name lines title desc; do
      if [ "$cat" != "$prev_cat" ]; then
        echo "  $cat:"
        prev_cat="$cat"
      fi
      echo "    - name: $name"
      echo "      lines: $lines"
      echo "      title: \"$(yaml_escape "$title")\""
      echo "      desc: \"$(yaml_escape "$desc")\""
    done
  } > "$tmp"

  # If content (excluding timestamp) hasn't changed, preserve existing timestamp
  if [ -f "$OUTPUT" ]; then
    local existing_no_ts current_no_ts
    existing_no_ts=$(grep -v '^generated:' "$OUTPUT" 2>/dev/null || echo "")
    current_no_ts=$(grep -v '^generated:' "$tmp" 2>/dev/null || echo "")
    if [ "$existing_no_ts" = "$current_no_ts" ]; then
      local old_ts
      old_ts=$(grep '^generated:' "$OUTPUT" | head -1)
      sed -i.bak "s/^generated:.*/$old_ts/" "$tmp"
      rm -f "$tmp.bak"
    fi
  fi

  mv "$tmp" "$OUTPUT"
  echo "Generated $OUTPUT ($skill_count skills, $agent_count agents)"
}

validate() {
  local tmp
  tmp=$(mktemp)
  # Generate to temp, compare with existing
  OUTPUT="$tmp" generate > /dev/null 2>&1 || true

  # Compare ignoring the generated timestamp line
  local existing_no_ts current_no_ts
  existing_no_ts=$(grep -v '^generated:' "$REPO_ROOT/.claude/inventory.yml" 2>/dev/null || echo "")
  current_no_ts=$(grep -v '^generated:' "$tmp" 2>/dev/null || echo "")

  if [ "$existing_no_ts" = "$current_no_ts" ]; then
    echo "✓ inventory.yml is up to date"
    rm -f "$tmp"
    return 0
  else
    echo "✗ inventory.yml is outdated. Run: ./scripts/generate-inventory.sh generate"
    diff <(echo "$existing_no_ts") <(echo "$current_no_ts") || true
    rm -f "$tmp"
    return 1
  fi
}

case "${1:-generate}" in
  generate) generate ;;
  validate) validate ;;
  *) echo "Usage: $0 [generate|validate]"; exit 1 ;;
esac
